#ifndef APPINFO_H
#define APPINFO_H

#define APPNAME "PLCsim"

#define MAJOR_VERSION "1"
#define MINOR_VERSION "4"
#define REVISION_VERSION "5"
#define VERSION MAJOR_VERSION "." MINOR_VERSION "." REVISION_VERSION
#define APPNAME_VERSION APPNAME " v" VERSION

#endif
